### ISSUE TITLE
HEVC multithreaded play is broken

### ISSUE THREAD

**Issue by Ryoandr** [lordmulder/mplayer-setup-win32#1]
log shows "get_format() cannot be called after ff_thread_finish_setup()" errors
Apparently it's fixed in recent versions of FFMPEG

**Comment by lordmulder** [comment]
Please understand that _this_ project is an **install script** for MPlayer. If you want report any bugs (or file any feature requests) _regarding the install script_, then this is the right place. Otherwise, for anything that belongs to MPlayer itself, you need to contact the [MPlayer team](http://mplayerhq.hu/) and/or the person providing the [Win32 Builds](http://oss.netfarm.it/mplayer-win32.php). If it's fixed in recent FFmpeg, re-compiling MPlayer with the latest libavcodec is what we need...
